"use strict";

const _ = require("lodash");
const convict = require("fit/convict");
const mongodbUri = require("mongodb-uri");

convict.addFormat({
    name: "mongo-uri",
    validate: function (val) {
        let parsed = mongodbUri.parse(val);
        mongodbUri.format(parsed);
    },
    coerce: function (urlString) {
        if (urlString) {
            let parsed = mongodbUri.parse(urlString);
            urlString = mongodbUri.format(parsed);
        }
        return urlString;
    },
});

const config = convict({
    enable_cors: {
        doc: "Enable Cors",
        format: Boolean,
        default: false,
        env: "ENABLE_CORS",
        arg: "enable_cors",
    },
    env: {
        doc: "node env",
        format: String,
        default: "development",
        env: "NODE_ENV",
        arg: "node_env",
    },
    // set to env name if env needs to be tested locally, e.g. if xcatalogz0 needs to be tested locally, set to 'xcatalogz0test'
    // (use values injected from local config for any local testing)
    // 'staging' if deployed on staging and not want to use local hardcoded values (use values injected from fik)
    // 'prod' if deployed to prod (use values injected from fik)
    environment: {
        doc: "env",
        format: String,
        default: "staging",
        env: "ENV",
        arg: "env",
    },
    mongo: {
        valar: {
            uri: {
                doc: "valar mongo",
                format: "mongo-uri",
                default: "mongodb://127.0.0.1:27017/valar",
                env: "MONGO_VALAR_READ_WRITE",
                arg: "mongo_valar_read_write",
            },
        },
        valar_high: {
            uri: {
                doc: "valar mongo - high critical",
                format: "mongo-uri",
                default: "mongodb://127.0.0.1:27017/valar_high",
                env: "MONGO_VALAR_HIGH_READ_WRITE",
                arg: "mongo_valar_high_read_write",
            },
        },
        valar_low: {
            uri: {
                doc: "valar mongo - low critical",
                format: "mongo-uri",
                default: "mongodb://127.0.0.1:27017/valar_low",
                env: "MONGO_VALAR_LOW_READ_WRITE",
                arg: "mongo_valar_low_read_write",
            },
        },
    },
    clickHouse: {
        cc_analytics: {
            uri: {
                doc: "analytic clickHouse",
                format: String,
                default: "http://localhost:8123",
                env: "CLICKHOUSE_CC_ANALYTICS_READ_WRITE",
                arg: "clickhouse_cc_analytics_read_write",
            },
        },
        audit_trail_allowed_actions: {
            doc: "Audit trail allowed events",
            format: String,
            default: "",
            env: "AUDIT_TRAIL_ALLOWED_EVENTS",
            arg: "audit_trail_allowed_events",
        },
    },
    port: {
        doc: "The port to bind",
        format: "port",
        default: 5070,
        env: "PORT",
        arg: "port",
    },
    baseURL: {
        doc: "The base url of the application",
        format: String,
        default: "https://api.sit.xcatalogz0.de/",
        env: "PLATFORM_COMMON_MAIN_URL",
        arg: "platform_common_main_url",
    },
    vilyaBaseUrl: {
        doc: "The base url to access vilya",
        format: String,
        default: "http://localhost:8123",
        env: "VILYA_BASE_URL",
        arg: "vilya_base_url",
    },
    vilyaInternalUrl: {
        doc: "Internal url for vilya",
        format: String,
        default: "http://localhost:5000",
        env: "VILYA_INTERNL_URL",
        arg: "vilya_internal_url",
    },
    vilyaInternalSVC: {
        doc: "Internal url for vilya",
        format: String,
        default: "https://api.sit.xcatalogz0.de/___/internal/assets",
        env: "VILYA_INTERNL_SVC",
        arg: "vilya_internl_svc",
    },
    nenyaInternalUrl: {
        doc: "Internal url for nenya",
        format: String,
        default: "https://api.xcatalogz5.de/___/internal/templates",
        env: "NENYA_INTERNL_URL",
        arg: "nenya_internal_url",
    },
    nenyaInternalSVC: {
        doc: "Internal url for nenya",
        format: String,
        default: "https://api.xcatalogz5.de/___/internal/templates",
        env: "NENYA_INTERNL_SVC",
        arg: "nenya_internal_svc",
    },
    ringilInternalSVC: {
        doc: "Internal url for ringil",
        format: String,
        default: "http://localhost:5000",
        env: "RINGIL_INTERNL_SVC",
        arg: "ringil_internal_svc",
    },
    nenyaPanelSVC: {
        doc: "Panel url for nenya",
        format: String,
        default: "https://api.xcatalogz5.de/service/panel/templates",
        env: "NENYA_PANEL_SVC",
        arg: "nenya_panel_svc",
    },
    redis: {
        redisLightspeedCache: {
            doc: "Redis URL of Valar service",
            format: String,
            default: "redis://localhost:6379/0",
            env: "REDIS_VALAR_READ_WRITE",
            arg: "redis_valar_read_write",
        },
        mithrandirLightspeedCache: {
            doc: "redis connection",
            format: String,
            default: "",
            env: "REDIS_MITHRANDIR_READ_ONLY",
            arg: "redis_mithrandir_read_only",
        }
    },
    application_domain_redis_prefix: "app:do",
    sentry: {
        dsn: {
            doc: "sentry url",
            format: String,
            default: "",
            env: "SENTRY_DSN",
            arg: "sentry_dsn",
        },
        environment: {
            doc: "sentry environment",
            format: String,
            default: "development",
            env: "SENTRY_ENVIRONMENT",
            arg: "sentry_environment",
        },
    },
    baseDomain: {
        doc: "The base url of the application",
        format: String,
        default: "https://console.sit.xcatalogz0.de/",
        env: "PLATFORM_COMMON_MAIN_DOMAIN",
        arg: "platform_common_main_domain",
    },
    balrogInternalSVC: {
        doc: "Internal svc for balrog",
        format: String,
        default: "",
        env: "BALROG_INTERNL_SVC",
        arg: "balrog_internl_svc",
    },
    mithrandirInternalSVC: {
        doc: "Internal svc for mithrandir",
        format: String,
        default: "",
        env: "MITHRANDIR_INTERNL_SVC",
        arg: "mithrandir_internl_svc",
    },
    vilyaBaseUrl: {
        doc: "The base url to access vilya",
        format: String,
        default: "http://localhost:8123",
        env: "VILYA_BASE_URL",
        arg: "vilya_base_url",
    },
    vilyaInternalUrl: {
        doc: "Internal url for vilya",
        format: String,
        default: "https://api.xcatalogz5.de/___/internal/assets",
        env: "VILYA_INTERNL_URL",
        arg: "vilya_internal_url",
    },
    nenyaInternalUrl: {
        doc: "Internal url for nenya",
        format: String,
        default: "https://api.xcatalogz5.de/___/internal/templates",
        env: "NENYA_INTERNL_URL",
        arg: "nenya_internal_url",
    },
    nenyaInternalSVC: {
        doc: "Internal url for nenya",
        format: String,
        default: "https://api.xcatalogz5.de/___/internal/templates",
        env: "NENYA_INTERNL_SVC",
        arg: "nenya_internal_svc",
    },
    palantirInternalSVC: {
        doc: "Internal url for palantir",
        format: String,
        default: "https://api.sit.xcatalogz0.de/___/internal/webhook",
        env: "PALANTIR_INTERNL_SVC",
        arg: "palantir_internal_svc",
    },
    logger: {
        level: {
            doc: "Logger Level",
            format: String,
            default: "error",
            env: "LOGGER_LEVEL",
            arg: "logger_level",
        },
    },
    mode: {
        doc: "app mode",
        format: String,
        default: "server",
        env: "MODE",
        arg: "mode",
    },
    server_type: {
        doc: "app mode",
        format: ["panel", "platform", "internal", "public"],
        default: "panel",
        env: "SERVER_TYPE",
        arg: "server_type",
    },
    milkbasket: {
        jwt_secret: {
            doc: "JWT Secret",
            format: String,
            default: "af11f899b01c7035cf1ff61dc154a1ff",
            env: "MB_JWT_SECRET",
            arg: "mb_jwt_secret",
        },
        jwt_expires: {
            doc: "JWT Expiry Time",
            format: String,
            default: "1h",
            env: "MB_JWT_EXPIRES",
            arg: "mb_jwt_expires",
        },
        mb_secret: {
            doc: "Milkbasket Secret",
            format: String,
            default: "d5cce374b1d0ebd1e25417ba455b2df9",
            env: "MB_SECRET",
            arg: "mb_secret",
        },
        mb_user: {
            doc: "Milkbasket User",
            format: String,
            default: "8de2420565a8a8620fd2c045",
            env: "MB_USER",
            arg: "mb_user",
        },
        mb_org: {
            doc: "Milkbasket Org",
            format: String,
            default: "22875b93-a78d-4d96-8177-57d7a6a6aacf",
            env: "MB_ORG",
            arg: "mb_org",
        },
        rr_product_id_code: {
            doc: "Milkbasket RRProductIdCode",
            format: String,
            default: "RR Product ID",
            env: "MILKBASKET_RR_PRODUCT_ID_CODE",
            arg: "milkbasket_rr_product_id_code",
        },
        rr_product_id_condition_code: {
            doc: "Milkbasket RR Product Id condition code ",
            format: String,
            default: "force-rr-id",
            env: "MILKBASKET_RR_PRODUCT_ID_CONDITION_CODE",
            arg: "milkbasket_rr_product_id_condition_code",
        }
    },
    relianceDigital: {
        jwt_secret: {
            doc: "JWT Secret",
            format: String,
            default: "af11f899b01c7035cf1ff61dc154a1ff",
            env: "RD_JWT_SECRET",
            arg: "rd_jwt_secret",
        },
        jwt_expires: {
            doc: "JWT Expiry Time",
            format: String,
            default: "1h",
            env: "RD_JWT_EXPIRES",
            arg: "rd_jwt_expires",
        },
        rd_secret: {
            doc: "Reliance Digital Secret",
            format: String,
            default: "9e24e9a72c949b9026a53c0ef340b303",
            env: "RD_SECRET",
            arg: "rd_secret",
        },
        rd_org: {
            doc: "Reliance Digital Org",
            format: String,
            default: "58c114c7-c54b-4c51-a031-5de882d4291d",
            env: "RD_ORG",
            arg: "rd_org",
        },
        rd_deal_price_code: {
            doc: "RD Deal Price Code",
            format: String,
            default: "10040",
            env: "RD_DEAL_PRICE_CODE",
            arg: "rd_deal_price_code",
        },
        romPriceInboundId: {
            doc: "relience deal price update inbound id",
            format: String,
            default: "656d85a4a70d81516d31dd52",
            env: "ROM_PRICE_INBOUND_ID",
            arg: "rom_price_inbound_id",
        },
        rd_channel_id: {
            doc: "rd channel id",
            format: String,
            default: "66ff91792e408f45b213f3cc",
            env: "RD_CHANNEL_ID",
            arg: "rd_channel_id",
        }
    },

    worker_mode: {
        doc: "app mode",
        format: [
            "external-catalog",
            "asset-worker",
            "relationship-bulk-worker",
            "bulk-update",
            "product-master-sync",
            "bulk-export",
            "bulk-plp-import",
            "relationship-export-worker",
            "retrigger-subscriber-sync",
            "product-delete",
            "product-restore",
            "platform_status",
            "skip-ca",
            "rule-execution-engine",
            "rule-manual-execution",
            "reflow",
            "ai-audit-bulk",
            "click-house-crud",
            "click-house-audit-trail",
            "bulk-import-process",
            "tracking-url-progress",
            "global_assets_processor",
            "unzip-asset-files",
            "tracking-asset-url-progress",
            "product-groceries-master-sync",
            "product-electronics-master-sync",
            "product-fashion-master-sync",
            "product-commongroup1-master-sync",
            "product-commongroup2-master-sync",
            "product-default-master-sync",
            "clickhouse-product-groceries-sync",
            "clickhouse-product-electronics-sync",
            "clickhouse-product-fashion-sync",
            "clickhouse-product-commongroup1-sync",
            "clickhouse-product-commongroup2-sync",
            "clickhouse-product-default-sync",
            "clickhouse-event-logs-sync",
            "clickhouse-data-model-sync",
            "solr-crud",
            "solr-product-groceries-sync",
            "solr-product-electronics-sync",
            "solr-product-fashion-sync",
            "solr-product-commongroup1-sync",
            "solr-product-commongroup2-sync",
            "solr-product-default-sync",
            "temp-product-sync",
            "jiomart-image-warmup",
        ],
        default: "external-catalog",
        env: "WORKER_MODE",
        arg: "worker_mode",
    },
    newrelic: {
        app_name: {
            doc: "new relic app name",
            format: String,
            default: "valor",
            env: "NEW_RELIC_APP_NAME",
            arg: "new_relic_app_name",
        },
        license_key: {
            doc: "new relic license key",
            format: String,
            default: "",
            env: "NEW_RELIC_LICENSE_KEY",
            args: "new_relic_license_key",
        },
    },
    kafka: {
        brokers: {
            doc: "Kafka Brokers List",
            format: String,
            default: "127.0.0.1:9092",
            env: "KAFKA_BROKER_LIST",
            arg: "kafka_broker_list",
        },
        topics: {
            doc: "Kafka Topics List",
            format: String,
            default: "",
            env: "KAFKA_TOPIC",
            arg: "kafka_topic",
        },
        max_bytes_per_partition: {
            doc: "The maximum amount of data per-partition the server will return. This size must be at least as large as the maximum message size the server allows or else it is possible for the producer to send messages larger than the consumer can fetch. If that happens, the consumer can get stuck trying to fetch a large message on a certain partition",
            format: Number,
            default: 1048576,
            env: "MAX_BYTES_PER_PARTITION",
            arg: "max_bytes_per_partition",
        },
        min_bytes: {
            doc: "The minimum amount of data the server should return for a fetch request. If the requested size is smaller than the minimum size, the consumer won't wait for that partition, and will get the remaining bytes available (up to the requested size) as soon as they are available or the request timeout occurs, whichever comes first.",
            format: Number,
            default: 1,
            env: "MIN_BYTES",
            arg: "min_bytes",
        },
        max_bytes: {
            doc: "The maximum amount of data the server should return for a fetch request. This is roughly analogous to batching messages in the sense that it can help the client achieve higher throughput by reducing the number of requests needed.",
            format: Number,
            default: 10485760,
            env: "MAX_BYTES",
            arg: "max_bytes",
        },
        max_wait_time_in_ms: {
            doc: "The maximum amount of time the server will wait to fill the request. This is roughly analogous to the maximum message size the server allows or else it is possible for the producer to send messages larger than the consumer can fetch. If that happens, the consumer can get stuck trying to fetch a large message on a certain partition",
            format: Number,
            default: 5000,
            env: "MAX_WAIT_TIME_IN_MS",
            arg: "max_wait_time",
        },
        heartbeat_interval: {
            doc: "Kafka heartbeat interval",
            format: Number,
            default: 10,
            env: "KAFKA_HEARTBEAT_INTERVAL",
            arg: "kafka_heartbeat_interval",
        },
        session_timeout: {
            doc: "Kafka session timeout",
            format: Number,
            default: 600,
            env: "KAFKA_SESSION_TIMEOUT",
            arg: "kafka_session_timeout",
        },
        connection_timeout: {
            doc: "Kafka connection timeout",
            format: Number,
            default: 5000,
            env: "KAFKA_CONNECTION_TIMEOUT",
            arg: "kafka_connection_timeout",
        },
    },
    smtp: {
        netcore: {
            doc: "netcore url",
            format: String,
            default:
                "smtp://gofyndfal:!CnccnC@smtp.falconide.com:587/?secure=true",
            env: "SMTP_NETCORE",
            arg: "smtp_netcore",
        },
    },
    emailProvider: {
        doc: "Email Provider",
        format: ["falconide"],
        default: "falconide",
        env: "EMAIL_PROVIDER",
        arg: "email_provider",
    },
    baseDomain: {
        doc: "The base domain of the platform",
        format: String,
        default: "https://console.xcatalogz0.de",
        env: "PLATFORM_COMMON_MAIN_DOMAIN",
        arg: "platform_common_main_domain",
    },
    cron_type: {
        doc: "cron type",
        format: String,
        default: "purge_products_cron",
        env: "CRON_TYPE",
        arg: "cron_type",
    },
    gcsCdn: {
        domain: {
            doc: "CDN Assets Domain",
            format: String,
            default: "cdn.pixelbin.io",
            env: "CDN_ITEM_DOMAINS",
            arg: "cdn_item_domains",
        },
        path: {
            doc: "CDN Assets path",
            format: String,
            default: "/v2/catalog-cloud-non-prod/ccl-np/original/",
            env: "CDN_ITEM_PATH",
            arg: "cdn_item_PATH",
        },
        bucket: {
            doc: "Storage Bucket",
            format: String,
            default: "ccl-assets",
            env: "STORAGE_FILE_ASSETS",
            arg: "storage_file_assets",
        },
        bucketPath: {
            doc: "Bucket base path",
            format: String,
            default: "organization/:orgId/documents/data/plp-export",
            env: "PLP_EXPORT_BUCKET_PATH",
            arg: "plp_exprot_bucket_path",
        },
        bucketPrefix: {
            doc: "Bucket Prefix",
            format: String,
            default: "xcatalogz0",
            env: "ASSETS_BUCKET_PREFIX",
            arg: "asset_bucket_prefix",
        },
    },
    baseValidationOrgList: {
        doc: "list of org ids to skip mime validation",
        format: String,
        default: "",
        env: "BASE_VALIDATION_ORGS",
        arg: "base_validation_orgs",
    },
    skipableCdns: {
        doc: "The cdns for which re upload is skipped",
        format: String,
        default:
            "https://cdn.pixelbin.io/v2/catalog-cloud-non-prod/ajioin/original/,https://cdn.pixelbin.io/v2/catalog-cloud-non-prod/infipr/original/",
        env: "SKIP_CDN_REUPLOAD",
        arg: "skip_cdn_reupload",
    },
    openAIKey: {
        doc: "OpenAI api key",
        format: String,
        default: "null",
        env: "OPENAI_API_KEY",
        arg: "openai_api_key",
    },
    boltic: {
        integration_url: {
            doc: "Access token url",
            format: String,
            default:
                "https://asia-south1.api.fcz0.de/service/webhook/fennel/integration/access_token",
            env: "BOLTIC_ACCESS_TOKEN_URL",
            arg: "boltic_access_token_url",
        },
        webhook_temporal_base_url: {
            doc: "Boltic execute url",
            format: String,
            default: "https://asia-south1.api.fcz0.de/service/webhook/temporal",
            env: "BOLTIC_WEBHOOK_BASE_URL",
            arg: "boltic_webhook_base_url",
        },
        panel_temporal_base_url: {
            doc: "Boltic panel url",
            format: String,
            default: "https://asia-south1.api.fcz0.de/service/panel/temporal",
            env: "BOLTIC_PANEL_BASE_URL",
            arg: "boltic_panel_base_url",
        },
        org_details_url: {
            doc: "Boltic org details url",
            format: String,
            default: "https://asia-south1.api.fcz0.de/service/web/organization",
            env: "BOLTIC_ORG_DETAILS_URL",
            arg: "boltic_org_details_url",
        },
        encryption_key: {
            doc: "Boltic encryption key",
            format: String,
            default: "",
            env: "BOLTIC_ENCRYPTION_KEY",
            arg: "boltic_encryption_key",
        },
        connect_domain: {
            doc: "Bolict connect",
            format: String,
            default: "https://connect.fcz0.de",
            env: "BOLTIC_CONNECT_DOMAIN",
            arg: "boltic_connect_domain",
        },
        source: {
            doc: "Bolict source param",
            format: String,
            default: "catalog-cloud",
            env: "BOLTIC_SOURCE_PARAM",
            arg: "boltic_source_param",
        },
    },
    ruleFailedStateMarkDuration: {
        doc: "Duration before which all rule execution history in pasued state will be marked as failed.",
        format: Number,
        default: 43200, // 12 hrs
        env: "RULE_FAILED_STATE_MARK_DURATION",
        arg: "rule_failed_state_mark_duration",
    },
    maxRetry: {
        doc: "Maximum retry allowed",
        format: Number,
        default: 20, //
        env: "MAX_RETRY",
        arg: "max_retry",
    },
    googleAi: {
        tokenExpiration: {
            doc: "Google AI token expiration time",
            format: Number,
            default: 3000, // 50 mins
            env: "GOOGLE_AI_TOKEN_EXPIRATION",
            arg: "google_ai_token_expiration",
        },
        apiTimeout: {
            doc: "Google API timout",
            format: Number,
            default: 240000,
            env: "GOOGLE_AI_API_TIMEOUT",
            arg: "google_ai_api_timeout",
        },
        url: {
            doc: "Google AI url",
            format: String,
            default: "https://3581-122-161-67-149.ngrok-free.app/dummy-gemini",
            env: "GOOGLE_AI_URL",
            arg: "google_ai_url",
        },
        imagesCountLimit: {
            doc: "Google AI images count limit",
            format: Number,
            default: 1000,
            env: "GOOGLE_AI_IMAGES_COUNT_LIMIT",
            arg: "google_ai_images_count_limit",
        },
    },
    service_name: {
        doc: "Service name",
        format: String,
        default: "valar",
        env: "SERVICE_NAME",
        arg: "service_name",
    },
    service_code: {
        doc: "Service name code",
        format: String,
        default: "VLR",
        env: "SERVICE_NAME_CODE",
        arg: "service_name_code",
    },
    tracing_enabled: {
        doc: "Tracing enabled",
        format: Boolean,
        default: true,
        env: "TRACING_ENABLED",
        arg: "tracing_enabled",
    },
    solr: {
        nodes: {
            doc: "Solr nodes (comma-separated host:port list)",
            format: String,
            default: "127.0.0.1:8983,127.0.0.2:8983",
            env: "SOLR_NODES",
            arg: "solr_nodes",
        },
        path: {
            doc: "Solr path",
            format: String,
            default: "/solr",
            env: "SOLR_PATH",
            arg: "solr_path",
        },
        secure: {
            doc: "Use secure connection for Solr",
            format: Boolean,
            default: false,
            env: "SOLR_SECURE",
            arg: "solr_secure",
        },
        username: {
            doc: "Solr username for authentication",
            format: String,
            default: "solr",
            env: "SOLR_USERNAME",
            arg: "solr_username",
        },
        password: {
            doc: "Solr password for authentication",
            format: String,
            default: "SolrRocks",
            env: "SOLR_PASSWORD",
            arg: "solr_password",
        },
    },
    zookeeper: {
        nodes: {
            doc: "Zookeeper connection string (comma-separated nodes, optional chroot)",
            format: String,
            default: "127.0.0.1:2181,127.0.0.2:2181",
            env: "COMMON_ZOOKEEPER_NODES",
            arg: "common_zookeeper_nodes",
        },
        username: {
            doc: "Zookeeper username for authentication",
            format: String,
            default: "admin",
            env: "ZOOKEEPER_USERNAME",
            arg: "zookeeper_username",
        },
        password: {
            doc: "Zookeeper password for authentication",
            format: String,
            default: "admin",
            env: "ZOOKEEPER_PASSWORD",
            arg: "zookeeper_password",
        },
        sessionTimeout: {
            doc: "Zookeeper session timeout in milliseconds",
            format: Number,
            default: 30000,
            env: "ZOOKEEPER_SESSION_TIMEOUT",
            arg: "zookeeper_session_timeout",
        },
        spinDelay: {
            doc: "Zookeeper spin delay in milliseconds",
            format: Number,
            default: 1000,
            env: "ZOOKEEPER_SPIN_DELAY",
            arg: "zookeeper_spin_delay",
        },
    },
});

// Perform validation
config.validate({ allowed: "strict" });

_.extend(config, config.get());

module.exports = config;
